"""Constants for the ONYX integration."""

DOMAIN = "hella_onyx"

ONYX_API = "onyx_api"
ONYX_CONFIG = "onyx_config"
ONYX_TIMEZONE = "onyx_timezone"

CONF_FINGERPRINT = "fingerprint"
CONF_LOCAL_ADDRESS = "local_address"
CONF_MIN_DIM_DURATION = "min_dim_duration"
CONF_MAX_DIM_DURATION = "max_dim_duration"
CONF_ADDITIONAL_DELAY = "additional_delay"
CONF_INTERPOLATION_FREQUENCY = "interpolation_frequency"

DEFAULT_SCAN_INTERVAL = 60
DEFAULT_ADDITIONAL_DELAY = 1000
DEFAULT_MIN_DIM_DURATION = 200
DEFAULT_MAX_DIM_DURATION = 2000
DEFAULT_INTERPOLATION_FREQUENCY = 5
MIN_INTERPOLATION_FREQUENCY = 0
MAX_INTERPOLATION_FREQUENCY = 10
MIN_ADDITIONAL_DELAY = 0
MAX_ADDITIONAL_DELAY = 20000
MIN_DIM_DURATION = 0
MAX_DIM_DURATION = 65535

MAX_BACKOFF_TIME = 1
