"""Constants for the ONYX integration."""

DOMAIN = "hella_onyx"

ONYX_API = "onyx_api"
ONYX_CONFIG = "onyx_config"
ONYX_TIMEZONE = "onyx_timezone"

CONF_FINGERPRINT = "fingerprint"
CONF_MIN_DIM_DURATION = "min_dim_duration"
CONF_MAX_DIM_DURATION = "max_dim_duration"

INCREASED_INTERVAL_DELTA = 1
DEFAULT_INTERVAL = 60
DEFAULT_MIN_DIM_DURATION = 200
DEFAULT_MAX_DIM_DURATION = 2000
MIN_DIM_DURATION = 0
MAX_DIM_DURATION = 65535

MAX_BACKOFF_TIME = 1
